% Channel details
channelID = 3211645;
readAPIKey = 'IN57T91RJ0C8NPFK';

% Get current second
currentSecond = second(now);  % returns 0–59

% Only send email if second < 10
if currentSecond > 5
    return  % skip rest of script
end


    data = thingSpeakRead(channelID, ...
        'ReadKey', readAPIKey, ...
        'NumPoints', 1);

    % Build email message
    msg = sprintf([ ...
        'Daily Soil Report\n\n' ...
        'Moisture: %.1f %%\n' ...
        'Temperature: %.1f °F\n' ...
        'EC: %.0f µS/cm\n' ...
        'pH: %.1f\n' ...
        'Nitrogen: %u mg/kg\n' ...
        'Phosphorus: %u mg/kg\n' ...
        'Potassium: %u mg/kg\n\n' ...
        'Timestamp: %s'], ...
        data(1), data(2), data(3), ...
        data(4), data(5), data(6), data(7), ...
        datestr(now, 'mm-dd-yyyy hh:MM:ss AM'));

    % ---- GOOGLE SCRIPT WEBHOOK ----
    url = 'https://script.google.com/macros/s/AKfycbyS74jKn1j84darHTpBxNhYeyUt1FjPamdQxCQlwMigW11UZXYsk8RJ--GSKHHeHcUI/exec';
    subject = 'Daily Soil Sensor Report';  % must be defined before payload

    payload = struct( ...
        'value1', subject, ...
        'value2', msg);

    try
        options = weboptions('MediaType','application/json');
        response = webwrite(url, payload, options);
    catch ME
        warning('Webhook sent, but MATLAB reported: %s', ME.message);
    end